api_platform:
  title: Hello API Platform
  version: 1.0.0
  formats:
    jsonld: ["application/ld+json"]
    json: ["application/json"]
  docs_formats:
    jsonld: ["application/ld+json"]
    jsonopenapi: ["application/vnd.openapi+json"]
    html: ["text/html"]
  defaults:
    pagination_client_enabled: true       # Ajout pour pouvoir activer/désactiver pagination côté client ds requête GET (ex : GET /books?pagination=false: disabled)
    pagination_client_items_per_page: true # Autorisation a modifier nbr items par page côté client (en rentrant "?itemsPerPage=10"dans l'URL)
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
    extra_properties:
      standard_put: true
      rfc_7807_compliant_errors: true

  keep_legacy_inflector: false
  use_symfony_listeners: true
